[build]
command = "npm run generate"
publish = "dist"

[context.production]
  environment = { NODE_VERSION = "16.13.1" }

[dev]
command = "npm run dev"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "/*"
  to = "/index.html#Error404"
  status = 404
