backend:
  name: git-gateway
  branch: dev # Branch to update (optional; defaults to master)
site_url: https://dev2020.itraws.com
# This lines should *not* be indented
publish_mode: editorial_workflow
locale: "en" # other languages, defaults to "en"
media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "Navigation"
    label: "navigation"
    description: "Site navigation"
    delete: false # prevent users from deleting documents in this collection
    editor:
      preview: false
    format: "json"
    folder: "assets/content"
    create: true
    slug: "{{slug}}-{{language}}"
    fields:
      - {
          label: "Language",
          name: "language",
          widget: "select",
          options: ["en", "fr"],
        }
      - { label: "Title", name: "title", widget: "string" }
      - label: "Navigation list"
        name: "navigation_list"
        widget: "list"
        types:
          - label: "Link"
            name: "link"
            widget: "object"
            fields:
              - { label: "Link Name", name: "link_name", widget: "string" }
              - { label: "Link Url", name: "link_url", widget: "string" }
              - {
                  label: "Link Display",
                  name: "link_display",
                  widget: "boolean",
                }
  - name: "contentPages" # Used in the UI
    label: "Content Pages" # Used in routes, e.g., /admin/collections/content
    format: "json"
    folder: "assets/content/page"
    create: true
    slug: "{{slug}}-{{language}}"
    fields:
      - {
          label: "Language",
          name: "language",
          widget: "select",
          options: ["en", "fr"],
        }
      - { label: "Title", name: "title", widget: "string" }
      - label: "Content List"
        name: "content_list"
        widget: "list"
        types:
          - label: "Hero content"
            name: "hero_content"
            widget: "object"
            fields:
              - { label: "Headline", name: "headline", widget: "string" }
              - { label: "Text", name: "text", widget: "text" }
              - {
                  label: "Button url",
                  name: "button_url",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Button value",
                  name: "button_value",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Button display",
                  name: "button_display",
                  widget: "boolean",
                  required: false,
                }
          - label: "Page content block"
            name: "page_content_block"
            widget: "object"
            fields:
              - { label: "Headline", name: "headline", widget: "string" }
              - { label: "Text", name: "text", widget: "text" }
              - {
                  label: "Image URL",
                  name: "image_url",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Image Upload",
                  name: "image_upload",
                  widget: "image",
                  required: false,
                }
              - {
                  label: "Image display",
                  name: "image_display",
                  widget: "boolean",
                  required: false,
                }
          - label: "Page content block with links"
            name: "page_content_block_links"
            widget: "object"
            fields:
              - { label: "Headline", name: "headline", widget: "string" }
              - { label: "Text", name: "text", widget: "text" }
              - label: "Section Links"
                name: "section_links"
                widget: "list"
                required: false
                types:
                  - label: "Link"
                    name: "link"
                    widget: "object"
                    fields:
                      - {
                          label: "Link Name",
                          name: "link_name",
                          widget: "string",
                        }
                      - {
                          label: "Link Url",
                          name: "link_url",
                          widget: "string",
                        }
          - label: "Products Content"
            name: "products_content"
            widget: "object"
            fields:
              - label: "Products and Services"
                name: "products"
                widget: "list"
                types:
                  - label: "Product"
                    name: "product"
                    widget: "object"
                    fields:
                      - {
                      label: "Image",
                      name: "image",
                      widget: "image",
                      required: false,
                        }
                      - { label: "Alt text", name: "alt_text", widget: "string" }
                      - { label: "Image url", name: "image_url", widget: "string" }
                      - {
                          label: "Image Display",
                          name: "image_display",
                          widget: "boolean",
                        }
      - {
          label: "Content Markdown",
          name: "content_markdown",
          widget: markdown,
          required: false,
        }
